version: "3.9"

name: "weather-forecast"

networks:
  weather-forecast-net:

services:
  postgres:
    image: "postgres"
    container_name: "weather-forecast-postgres"
    networks:
      - weather-forecast-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: "redis"
    container_name: "weather-forecast-redis"
    networks:
      - weather-forecast-net
    ports:
      - "6379:6379"
  app:
    container_name: "weather-forecast-app"
    image: "weather-forecast-app-img"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - weather-forecast-net
    ports:
      - "5022:80"
    environment:
       ASPNETCORE_ENVIRONMENT: Production
       DOTNET_PRINT_TELEMETRY_MESSAGE: false
       ConnectionStrings__Postgres: Host=weather-forecast-postgres;Username=postgres;Password=postgres;Database=postgres
       ConnectionStrings__Redis: weather-forecast-redis:6379
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started