GET http://localhost:5298/health

###

POST http://localhost:5298/ads
Content-Type: application/json

{
    "Location": "Moscow"
}

###

POST http://localhost:5298/ads
Content-Type: application/json

{
    "Location": "Москва"
}

###

POST http://localhost:5298/ads
Content-Type: application/json

{
    "Location": "London"
}